# =======================================================================
# Change settings here
#
# Utils:
#   - YAML Quick Reference card: http://www.yaml.org/refcard.html
#   - YAML.org: http://yaml.org/
#   - YAML Specification: http://yaml.org/spec/
#   - YAML Lint: https://codebeautify.org/yaml-validator
#   - YAML Validator: https://yamlvalidator.com/
# =======================================================================
VERSION: Saiku-
LICENSE: null
BIPLUGIN: false
BIPLUGIN5: false
TOMCAT_WEBAPP: /saiku
REST_MOUNT_POINT: /rest/saiku/
DIMENSION_PREFETCH: true
DIMENSION_SHOW_ALL: true
# Valid values for DIMENSION_HIDE_HIERARCHY:
# 1) NONE
# 2) SINGLE_LEVEL
# 3) ALL
DIMENSION_HIDE_HIERARCHY: SINGLE_LEVEL
ERROR_LOGGING: false
I18N_LOCALE: en
# Number of erroneous ajax calls in a row before UI cant recover
ERROR_TOLERANCE: 3
QUERY_PROPERTIES:
  saiku.olap.query.automatic_execution: true
  saiku.olap.query.nonempty: true
  saiku.olap.query.nonempty.rows: true
  saiku.olap.query.nonempty.columns: true
  saiku.ui.render.mode: table
  saiku.olap.query.filter: true
  saiku.olap.result.formatter: flattened
REPOSITORY_LAZY: false
TABLE_LAZY: true # Turn lazy loading off / on
TABLE_LAZY_SIZE: 1000 # Initial number of items to be rendered
TABLE_LAZY_LOAD_ITEMS: 20 # Additional item per scroll
TABLE_LAZY_LOAD_TIME: 20 # Throttling call of lazy loading items
# Valid values for CELLSET_FORMATTER:
# 1) flattened
# 2) flat
CELLSET_FORMATTER: flattened
# Limits the number of rows in the result
# 0 - no limit
RESULT_LIMIT: 0
MEMBERS_FROM_RESULT: true
MEMBERS_LIMIT: 3000
MEMBERS_SEARCH_LIMIT: 75
ALLOW_IMPORT_EXPORT: false
ALLOW_PARAMETERS: true
PLUGINS:
  - Chart
DEFAULT_VIEW_STATE: view # Could be 'edit' as well
DEMO: false
TELEMETRY_SERVER: 'http://telemetry.analytical-labs.com:7000'
LOCALSTORAGE_EXPIRATION: 36000000 # 10 hours, in ms
UPGRADE: true
EVALUATION_PANEL_LOGIN: true
QUERY_OVERWRITE_WARNING: true
MAPS: true
MAPS_TYPE: OSM # OSM || GMAPS
MAPS_TILE_LAYER:
  OSM:
    map_marker: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
    map_heat: 'https://otile{s}-s.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.png'
  GMAPS: null
MAPS_OPTIONS:
  OSM:
    maxZoom: 18
    attribution: '<a href="http://osm.org/copyright" target="_blank">OpenStreetMap</a>'
  GMAPS: null
MAPS_OSM_NOMINATIM: 'https://nominatim.openstreetmap.org/' # http://wiki.openstreetmap.org/wiki/Nominatim
DATA_SOURCES_LOOKUP: false
DEFAULT_REPORT_SHOW: false
DEFAULT_REPORTS:
  admin:
    -
      path: ADD_PATH1 # Example: /homes/home:admin/chart.saiku
      visible: false
  _:
    -
      path: ADD_PATH2
      visible: false
  ROLE_ADMIN:
    -
      path: ADD_PATH3
      visible: false
PARENT_MEMBER_DIMENSION: false
EXT_DATASOURCE_PROPERTIES: false
SHOW_USER_MANAGEMENT: true
SHOW_REFRESH_NONADMIN: false
EMPTY_VALUE_CHARACTER: '-'
HIDE_EMPTY_ROWS: true
MEASURE_GROUPS_COLLAPSED: false
ORBIS_AUTH:
  enabled: false
  cookieName: COOKIE_NAME
SCHEMA_EDITOR:
  # The `^` matches beginning of input
  STAR_SCHEMA_FACT_TABLE: !!js/regexp /^fact_|^f_/i
  STAR_SCHEMA_DIMENSION_TABLE: !!js/regexp /^dimension_|^dim_|^d_/i
  STAR_SCHEMA_MEASURE_COLUMN: !!js/regexp /^measure_|^m_/i
  # The `$` matches end of input
  STAR_SCHEMA_MEASURE_AGGREGATION_COLUMN: !!js/regexp /_sum$|_avg$|_count$|_min$|_max$/i
ALLOW_TABLE_DATA_COLLAPSE: false
ALLOW_AXIS_COLUMN_TITLE_TABLE: true
COLUMN_TITLE_TABLE_USE_LEVEL_CAPTION_NAME: true
INTRO_FILE_NAME: Workspace
# For more options, see: http://introjs.com/docs/intro/options/
INTRO_DEFAULT_OPTIONS:
  showStepNumbers: true
  showBullets: false
  showProgress: true
# For more info, see: https://github.com/aml-development/ozp-iwc
OZP_IWC_ENABLED: false
OZP_IWC_CLIENT_URI: 'http://aml-development.github.io/ozp-iwc'
# /{minor}/{major}/{action} ("/application/json/view")
# or
# /{minor}/{major}/{action}/{handlerId} ("/application/json/view/123")
OZP_IWC_REFERENCE_PATH:
  intro: /application/display/help
  time_series_filter: /application/commonComponent/timeline/setTimes
OZP_IWC_CONFIG:
  label: 'Saiku Analytics'
  icon: 'https://avatars0.githubusercontent.com/u/1043666?v=3&s=32'
TIME_SERIES_FILTER:
  enabled: true
  # Here are some valid date formats:
  # more info here: http://dygraphs.com/data.html
  #
  # 2009-07-12
  # 2009/07/12
  # 2009/07/12 12
  # 2009/07/12 12:34
  # 2009/07/12 12:34:56
  date_format: YYYY/MM/DD
EXTENDED_REPOSITORY_RESOURCE: false
